### ISSUE TITLE
Missing ouputPath

### ISSUE THREAD

**Issue by SimenB** [alexpalombaro/modernizr-webpack-plugin#1]
The filepath injected into the HTML is missing the `outputPath` prefix. The bundled file is put into the right directory, but the path in the html file is wrong. (`meep.js` is my app-bundle)

![image](https://cloud.githubusercontent.com/assets/1404810/10468449/6a26d866-71ff-11e5-84cd-c560b71efd18.png)

**Comment by alexpalombaro** [comment]
@SimenB  have taken a look at how html-webpack-plugin resolves the publicPath from the webpack compiler and used that method to make it more seamless for the user. Thanks for reviewing the code and lodging the issue! :smiley:

**Comment by SimenB** [comment]
Awesome! Probably a better approach, yeah :smile:
