### ISSUE TITLE
Install modernizr required ? [Question]

### ISSUE THREAD

**Issue by Squidies** [alexpalombaro/modernizr-webpack-plugin#18]
Is it required to *also* install modernizr as well as the plugin?

Following the directions according to the README, I could not understand why a modernizr-bundle.js file was not being created. Finally ran `npm install modernizr --save-dev` and was able to generate the file as expected. 

If it is ***also*** required to download and install Modernizr into the project, please reference this in the directions in README.

**Comment by SimenB** [comment]
It is already defined as a dep (https://github.com/alexpalombaro/modernizr-webpack-plugin/blob/72caa494bee5c409067d09b32835575515ef0c9a/package.json#L33), can you provide a reproducing example config?

**Comment by Squidies** [comment]
My apologies. The file is being generated (without the need to additionally install modernizr) and seems to be functioning. I may have wrongfully assumed that it would automatically be inserted into the `<head>` of the document. Once I added a link to the file everything loaded correctly.
