### ISSUE TITLE
[hash] vs [chunkhash]

### ISSUE THREAD

**Issue by TigerC10** [alexpalombaro/modernizr-webpack-plugin#19]
Looks like `modernizr-webpack-plugin` does not adhere to webpack naming conventions for filename string substitution.  Per webpack conventions:

`[hash]` - build hash
`[chunkhash]` - file hash

At present, `modernizr-webpack-plugin` only supports filename string substitution `[hash]`, but instead provides a chunkhash instead of using the build's hash (#6).  It would be great if `modernizr-webpack-plugin` could get behind the webpack naming conventions and use `[chunkhash]` instead of `[hash]` for current functionality (as well as offer the correct `[hash]` string subtitution functionality).

**Comment by alexpalombaro** [comment]
Merged fix from pull request
