### ISSUE TITLE
Please add support for Webpack 4.8.3

### ISSUE THREAD

**Issue by blachawk** [alexpalombaro/modernizr-webpack-plugin#27]
I have Webpack 4.8.3 installed, along with modernizr-webpack-plugin version 1.0.7. I have followed all the instructions on your [npm page](https://www.npmjs.com/package/modernizr-webpack-plugin) in regards to how to install it.  The process was easy for me.  But when I load project through the browser after a successful `npm start` action, no classes are added to the DOM from modernizr.

I tried clearing my cache, restarting my server and getting ideas from other web pages.  No luck.

Please help, you're my only hope.

**Comment by strobox** [comment]
Works well with *"webpack": "^4.20.2"*, but   but didn't work with *"html-webpack-plugin": "^4.0.0-alpha"*, so try to use this plugin with `htmlWebpackPlugin: false` temporary

**Comment by strobox** [comment]
It will be published at *http://localhost:8081/modernizr-bundle.js*
