### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by rejas** [alexpalombaro/modernizr-webpack-plugin#33]
As mentioned in https://github.com/Modernizr/Modernizr/issues/2499 this project doesnt work anymore with the latest modernizr version since this one here still relies on old and unmaintained node versions. 

Due to its updated dependencies modernizr needs at least node >= 10.

So I am wondering if anyone still maintains it?

**Comment by DanielRuf** [comment]
> Due to its updated dependencies modernizr needs at least node >= 10.

Which will break webpack 4 support ;-)
See also https://github.com/webpack/webpack/blob/v4.41.6/package.json#L87

**Comment by neutraali** [comment]
Last commit was `Feb 16 2018` - Assume dead.

**Comment by DanielRuf** [comment]
I could create a fork of it but so far it seems not many use this plugin: https://www.npmjs.com/package/modernizr-webpack-plugin

See also https://github.com/peerigon/modernizr-loader/issues/44

So I think the best solution is really to directly use modernizr.
